# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daf80966b6907da04d5e3946b8d24c66d2b68fe0a896a3bb3acf250c65c9ad05bf9666cb677a27b937685caa89798e0ca93238e11d658cbf8a078ef52792a97d

test:
  secret_key_base: 20b1b481e8e8b04dfa4392da3f76f2adea478f2c46bd23e3eccdaf3336e808026f2cd0c2353455cee4a3b2533c1d0eb6bdd10ddec51a295105c886decc6d2e3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
